sudo: false
language: python

env:
  global:
    PYTEST_ADDOPTS="--cov=vint --cov=test --cov-report=xml --cov-report=term-missing:skip-covered"

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# Travis makes it hard to use py37.
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install tox tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -X search gcov pycov -f coverage.xml --required
  # coveralls only support one env.
  - if [ "$TOXENV" = py36 ]; then pip install coveralls; coveralls; fi

notifications:
  email: false
