language: python

notifications:
  email: false

python:
  - "2.7"
  - "3.4"

install:
  - pip install -e .

script:
  - PATH="./bin:$PATH" py.test -vv --cov vint test

after_success:
  coveralls --verbose
