sudo: false
language: python

env:
  global:
    PYTEST_ADDOPTS="--cov vint --cov-report=xml --cov-report=term-missing:skip-covered"

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install tox tox-travis pytest-cov

script:
  - tox

after_success:
  - pip install codecov coveralls
  # coveralls only support one env.
  - if [ "$TOXENV" = py36 ]; then coveralls; fi
  - codecov -X search gcov pycov -f coverage.xml

notifications:
  email: false
