language: python

python: 3.4

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=coverage

install:
  - pip install tox
  - if test "$TOXENV" = coverage ; then pip install python-coveralls ; fi

script: tox

after_success:
  - if test "$TOXENV" = coverage ; then coveralls ; fi

notifications:
  email: false
