language: python
dist: xenial

git:
  submodules: false

env:
  global:
    PYTEST_ADDOPTS="--cov-report=xml"

jobs:
  include:
    - name: Python 3.7 (integration)
      python: "3.7"
      env:
        - TOXENV=py37-cov
        # Fail on (internal) deprecation warnings.
        - PYTEST_ADDOPTS="$PYTEST_ADDOPTS -Werror::DeprecationWarning -Wonce::DeprecationWarning:.*[/\\](_bundles|site-packages)[/\\]"
      git:
        # Check out vital.vim for test_cli_vital.
        submodules: true

install:
  - pip install tox

script:
  - tox

after_success:
  - |
    if [[ "${TOXENV%-cov}" != $TOXENV ]]; then
      bash <(curl -s https://codecov.io/bash) -f coverage.xml -X fix

      pip install coveralls
      COVERALLS_PARALLEL=true coveralls
    fi

notifications:
  email: false
  webhooks: https://coveralls.io/webhook
