language: python

notifications:
  email: false

python:
  - "3.4"

install:
  - pip install -U -r requirements.txt --use-mirrors
  - pip install -U -r test-requirements.txt --use-mirrors

script:
  - py.test --cov vint test

after_success:
  coveralls --verbose
