language: python

python: 3.4

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=coverage

install:
  - travis_retry pip install coveralls
  - travis_retry pip install tox

script: tox

after_success:
  - if test "$TOXENV" = coverage ; then coveralls ; fi

notifications:
  email: false
